[package]
name = "bitcoinz-wallet-lite"
version = "0.1.0"
edition = "2018"
authors = ["BitcoinZ Community"]
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["embed_params"]
embed_params = ["zecwalletlitelib/embed_params"]
zfuture = []


[dependencies.neon]
version = "0.8"
default-features = false
features = ["napi-6"]

[dependencies]
# Using BitcoinZ-specific version of the wallet library (included in repo)
zecwalletlitelib = { path = "../lib" }
#zecwalletlitelib = { git = "https://github.com/adityapk00/zecwallet-light-cli" }
#zecwalletlitelib = { path = "../../zecwallet-light-cli/lib" }
lazy_static = "1.4.0"


[patch.crates-io]
zcash_address = { git = "https://github.com/z-bitcoinz/librustzcash-bitcoinz", rev = "8190688b" }
zcash_primitives = { git = "https://github.com/z-bitcoinz/librustzcash-bitcoinz", rev = "8190688b" }
zcash_client_backend = { git = "https://github.com/z-bitcoinz/librustzcash-bitcoinz", rev = "8190688b" }
zcash_note_encryption = { git = "https://github.com/z-bitcoinz/librustzcash-bitcoinz", rev = "8190688b" }
zcash_encoding = { git = "https://github.com/z-bitcoinz/librustzcash-bitcoinz", rev = "8190688b" }
zcash_proofs = { git = "https://github.com/z-bitcoinz/librustzcash-bitcoinz", rev = "8190688b" }
orchard = { git = "https://github.com/z-bitcoinz/orchard-bitcoinz", branch = "bitcoinz-21b-supply" }
