name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for (e.g., v1.0.2)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}

      - name: Download all artifacts from tag build
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-and-sign.yml
          workflow_conclusion: success
          name_is_regexp: true
          name: BitcoinZ-Blue-.*
          path: ./artifacts

      - name: List downloaded artifacts
        run: |
          echo "📦 Downloaded artifacts:"
          find ./artifacts -name "*.zip" -o -name "*.exe" -o -name "*.AppImage" -o -name "*.deb" | sort

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          name: BitcoinZ Blue ${{ inputs.tag }} - Cross-Platform Release
          body: |
            # 🎉 BitcoinZ Blue ${{ github.ref_name }} - Complete Cross-Platform Release

            ## ✅ What's New

            ### 🚀 **Complete Cross-Platform Support**
            - **Windows**: Setup installer + portable ZIP
            - **macOS**: Universal app (Intel + Apple Silicon)
            - **Linux**: AppImage + DEB package

            ### 💎 **BitcoinZ Features**
            - Full BitcoinZ blockchain support
            - Native Rust performance optimizations
            - Secure wallet functionality
            - Transaction management
            - Address book integration
            - Modern UI with blue gradient theme

            ### 🔧 **Technical Achievements**
            - Rust 1.81 native modules for maximum performance
            - Node.js 17 compatibility
            - Automated build pipeline
            - Security scanning integration
            - Code signing for all platforms

            ## 📦 **Download Options** ⬇️

            ### 🪟 **Windows (x64)**
            - **Setup Installer** - Download from `BitcoinZ-Blue-Windows-Installer` (Recommended)
            - **Portable Version** - Download from `BitcoinZ-Blue-Windows-Portable` (No installation required)

            ### 🍎 **macOS**
            - **Apple Silicon (M1/M2/M3)** - Download from `BitcoinZ-Blue-macOS-AppleSilicon`
            - **Intel CPUs** - Download from `BitcoinZ-Blue-macOS-Intel`

            ### 🐧 **Linux**
            - **Universal AppImage** - Download from `BitcoinZ-Blue-Linux-AppImage` (Recommended)
            - **Debian/Ubuntu Package** - Download from `BitcoinZ-Blue-Linux-DEB`

            ## 🔒 **Security**
            - All applications are code-signed
            - Automated vulnerability scanning
            - Secure build environment
            - Open source and auditable

            ## 🛠 **Installation**

            ### Windows
            1. Download the setup.exe file
            2. Run the installer
            3. Follow the setup wizard

            ### macOS
            1. Download the appropriate ZIP for your CPU
            2. Extract and move to Applications folder
            3. Right-click and "Open" to bypass Gatekeeper

            ### Linux
            1. Download the .AppImage file
            2. Make executable: `chmod +x BitcoinZ\ Blue-*.AppImage`
            3. Run: `./BitcoinZ\ Blue-*.AppImage`

            ---

            **Built with ❤️ for the BitcoinZ community**

            **Auto-generated from successful builds**
          files: |
            ./artifacts/**/*
          draft: false
          prerelease: false
